### ISSUE TITLE
[Bug] error parsing input: strconv.ParseFloat: parsing "---": invalid syntax

### ISSUE THREAD

**Issue by b17k0** [JFryy/qq#33]
Hi! I'm having issues with how the program handles YAML files.

Given this file (config.yml.dist):
```yaml
---
db_host: "localhost"
db_port: 5432
db_user: "postgres"
db_password: ""
db_name: "postgres"
server_port: 8080
api_key: ""
```

When I try to convert it directly:
```
$ qq config.yml.dist -i yaml -o json
error parsing input: strconv.ParseFloat: parsing "---": invalid syntax
null
```

If I remove the YAML header (---) and run the command again:
```
$ qq config.yml.dist -i yaml -o json
error parsing input: invalid character 'd' looking for beginning of value
null
```

However, using cat and piping the content works fine in both cases:

```
$ cat config.yml.dist | qq -i yaml -o json
{
  "api_key": "",
  "db_host": "localhost",
  "db_name": "postgres",
  "db_password": "",
  "db_port": 5432,
  "db_user": "postgres",
  "server_port": 8080
}
```

Also, converting the YAML to INI doesn't work -it returns an empty result:

```
$ cat config.yml.dist | qq -i yaml -o ini
# returns nothing
```
